name: Demo
on:
  push:
    branches:
      - '*'

jobs:
  demo-job:
    name: 'Build job'
    runs-on: ubuntu-latest
    steps:
      - name: 'Start build job'
        run: |
        echo "Hello world"

      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Java'
        uses: actions/setup-java@v1

      - name: 'Check Java Version'
        run: |
          java --version
